
extern zend_class_entry *cyant_eventmanager_sharedeventmanagerawareinterface_ce;

ZEPHIR_INIT_CLASS(Cyant_EventManager_SharedEventManagerAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_cyant_eventmanager_sharedeventmanagerawareinterface_setsharedmanager, 0, 0, 1)
	ZEND_ARG_INFO(0, sharedEventManager)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(cyant_eventmanager_sharedeventmanagerawareinterface_method_entry) {
	PHP_ABSTRACT_ME(Cyant_EventManager_SharedEventManagerAwareInterface, setSharedManager, arginfo_cyant_eventmanager_sharedeventmanagerawareinterface_setsharedmanager)
	PHP_ABSTRACT_ME(Cyant_EventManager_SharedEventManagerAwareInterface, getSharedManager, NULL)
	PHP_FE_END
};
