cyant.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant.c -o cyant.lo 
kernel/main.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/alternative/fcall.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/alternative/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/alternative/fcall.c -o kernel/alternative/fcall.lo 
kernel/file.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/kernel/concat.c -o kernel/concat.lo 
cyant/eventmanager/event.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/event.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/event.c -o cyant/eventmanager/event.lo 
cyant/eventmanager/eventinterface.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/eventinterface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/eventinterface.c -o cyant/eventmanager/eventinterface.lo 
cyant/eventmanager/eventmanager.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/eventmanager.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/eventmanager.c -o cyant/eventmanager/eventmanager.lo 
cyant/eventmanager/eventmanagerinterface.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/eventmanagerinterface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/eventmanagerinterface.c -o cyant/eventmanager/eventmanagerinterface.lo 
cyant/eventmanager/listeneraggregateinterface.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/listeneraggregateinterface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/listeneraggregateinterface.c -o cyant/eventmanager/listeneraggregateinterface.lo 
cyant/eventmanager/responsecollection.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/responsecollection.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/responsecollection.c -o cyant/eventmanager/responsecollection.lo 
cyant/eventmanager/sharedeventmanagerawareinterface.lo: /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/sharedeventmanagerawareinterface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/antoine/Workspace/ZephirEvm/cyant/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/antoine/Workspace/ZephirEvm/cyant/ext/cyant/eventmanager/sharedeventmanagerawareinterface.c -o cyant/eventmanager/sharedeventmanagerawareinterface.lo 
$(phplibdir)/cyant.la: ./cyant.la
	$(LIBTOOL) --mode=install cp ./cyant.la $(phplibdir)

./cyant.la: $(shared_objects_cyant) $(CYANT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_cyant) $(CYANT_SHARED_LIBADD)

